server:
  port: 9300
spring:
  application:
    name: pulsesg-task-service
  couchbase:
    bootstrap-hosts: 52.91.169.220
    bucket:
      name: generatedata
      password: Generated123!
  data:
    couchbase:
      auto-index: true
couchDB:
  login:
    userName: generated
LOGGING_ROOT: C:/workspace/logs/pulsesg/server