main:
  business:
    uri: /v1/task
logging:
  level:
    org.springframework.data.couchbase.repository.query: DEBUG
server:
  port: 9300
spring:
  application:
    name: pulsesg-task-service
  couchbase:
    bootstrap-hosts: 127.0.0.1
    bucket:
      name: generatedata
      password: Panja@05
  data:
    couchbase:
      auto-index: true
validations:
  task:
    date-pattern: yyyy-MM-dd HH:mm:ss
couchDB:
  login:
    userName: Administrator
LOGGING_ROOT: C:/workspace/logs/pulsesg/server

# hystrix changes
hystrix:
  command:
    taskService-addNewTask:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 10
      cicuitBreaker:
        enabled: true
        requestVolumeThreshold: 30
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 90
        forceOpen: false
  threadpool:
    taskService-addNewTask:
      coreSize: 2
      maximumSize: 5
      queueSizeRejectionThreshold: 5
      allowMaximumSizeToDivergeFromCoreSize: true