logging:
  level:
    org.springframework.data.couchbase.repository.query: DEBUG
server:
  port: 9300
spring:
  profiles:
    active: local
  application:
    name: pulsesg
  couchbase:
    bootstrap-hosts: 52.91.169.220
    bucket:
      name: generatedata
      password: Generated123!
  data:
    couchbase:
      auto-index: true
validations:
  task:
    date-pattern: yyyy-MM-dd HH:mm:ss
couchDB:
  login:
    userName: generated

