server:
  port: 9300
spring:
  application:
    name: pulsesg-task-service
  couchbase:
    bootstrap-hosts: 127.0.0.1
    bucket:
      name: generatedata
      password: Panja@05
  data:
    couchbase:
      auto-index: true
couchDB:
  login:
    userName: Administrator
LOGGING_ROOT: C:/workspace/logs/pulsesg/server